# Generated by Django 3.0.8 on 2020-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdiarymodel',
            name='memo2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdiarymodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
