# Generated by Django 3.0.8 on 2020-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_app1', '0002_auto_20200805_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdiarymodel',
            name='memo3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
