# Generated by Django 3.0.8 on 2020-07-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_app1', '0003_auto_20200720_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdiarymodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付入力'),
        ),
    ]
