# Generated by Django 3.0.8 on 2020-07-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_app1', '0005_auto_20200722_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdiarymodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdiarymodel',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
